FROM orcidhub/app AS orcidhub-dev

LABEL maintainer="The University of Auckland" \
      description="NZ ORCiD Hub Application Image with Development support"
ARG http_proxy
ENV http_proxy=${http_proxy} https_proxy=${http_proxy} ftp_proxy=${http_proxy}

COPY dev_requirements.txt /dev_requirements.txt
COPY test_requirements.txt /test_requirements.txt
COPY requirements.txt /requirements.txt

RUN dnf install -y git \
 && dnf clean all \
 && rm -rf /var/cache/dnf \
 && pip install -U -r /dev_requirements.txt \
 && (chmod +x /etc/shibboleth/shibd-redhat 2>/dev/null || true) \
 && rm -rf $HOME/.pip/cache /dev_requirements.txt /requirements.txt

ENV DEBUG=1
WORKDIR /src
