{
  "swagger" : "2.0",
  "info" : {
    "version" : "Latest",
    "title" : "ORCID Member"
  },
  "host" : "api.orcid.org",
  "tags" : [ {
    "name" : "Member API v2.1"
  }, {
    "name" : "Member API v2.0"
  }, {
    "name" : "Development Member API v3.0_dev1"
  }, {
    "name" : "resources"
  } ],
  "paths" : {
    "/v2.0/client/{client_id}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClient",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.0/group-id-record" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecords",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordJSON",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.0/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordJSON",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.0/search" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryXML",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.0/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivities",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/address" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddresses",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiography",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducations",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/email" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmployments",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiers",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundings",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywords",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationJSON",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.0/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.0/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNames",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviews",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/person" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPerson",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrls",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/works" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}{ignore}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecord",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClient",
        "security" : [ {
          "orcid_auth" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.1/group-id-record" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecords",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordJSON",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.1/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecord",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordJSON",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecord",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.1/search" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryXML",
        "security" : [ {
          "orcid_auth" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivities",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddresses",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiography",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducations",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmployments",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiers",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundings",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywords",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationJSON",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.1/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNames",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviews",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPerson",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrls",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}{ignore}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecord",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClient",
        "security" : [ {
          "orcid_auth" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_dev1/group-id-record" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecords",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordJSON",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_dev1/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecord",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordJSON",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecord",
        "security" : [ {
          "orcid_auth" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_dev1/search" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryXML",
        "security" : [ {
          "orcid_auth" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivities",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddresses",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiography",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/education" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducations",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmployments",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiers",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundings",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywords",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationJSON",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNames",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNameJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviews",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPerson",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetails",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrls",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlJSON",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/work" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummary",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkJSON",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/read-limited" ]
        } ]
      }
    },
    "/v3.0_dev1/{orcid}{ignore}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_dev1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecord",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "orcid_two_legs" : {
      "type" : "oauth2",
      "tokenUrl" : "https://pub.orcid.org/oauth/token",
      "flow" : "application",
      "scopes" : {
        "/group-id-record/update" : "Update groups",
        "/premium-notification" : "Notifications",
        "/group-id-record/read" : "Read groups",
        "/read-public" : "Read Public record"
      }
    },
    "orcid_auth" : {
      "type" : "oauth2",
      "authorizationUrl" : "https://orcid.org/oauth/authorize",
      "tokenUrl" : "https://pub.orcid.org/oauth/token",
      "flow" : "accessCode",
      "scopes" : {
        "/read-limited" : "Read Limited record",
        "/activities/update" : "Update activities",
        "/person/update" : "Update person"
      }
    }
  }
}