#!/bin/bash

# Set up the configuration:
if [ -z "$ORCID_CLIENT_ID" ] || [ -z "$ORCID_CLIENT_SECRET" ] ; then
  echo "Missing Orcid API client ID (\$ORCID_CLIENT_ID) and/or secret (\$ORCID_CLIENT_SECRET)"
  exit 78 # /* configuration error */
fi
## Runtime environment name:
ENV=${ENV:-test}
echo "Runtime Environment: $ENV"
## host domainnname:
DOMAINNAME=${DOMAINNAME:-$(hostname -A | cut -d\  -f1)}
HOSTNAME=${HOSTNAME-$(hostname)}

echo "Domain name: \"$DOMAINNAME\""
echo "Host anem: \"$HOSTNAME\""

## Shibboleth SP domainname:
[ -z "$SHIB_SP_DOMAINNAME" ] && SHIB_SP_DOMAINNAME=${DOMAINNAME/$HOSTNAME/$ENV}
echo "Shibboleth SP Domainname (\$SHIB_SP_DOMAINNAME): \"$SHIB_SP_DOMAINNAME\""

## Shibboleth SP domainname:
if [ -z "$SHIB_IDP_DOMAINNAME" ] ; then
  if [ "$ENV" != "prod" ] ; then
    SHIB_IDP_DOMAINNAME=directory.test.tuakiri.ac.nz
  else 
    SHIB_IDP_DOMAINNAME=directory.tuakiri.ac.nz
  fi
fi
echo "Shibboleth IdP Domainname (\$SHIB_IDP_DOMAINNAME): $SHIB_IDP_DOMAINNAME"

[ -z "$SHIB_SSO_DS_URL" ] && SHIB_SSO_DS_URL=https://${SHIB_IDP_DOMAINNAME}/ds/DS
echo "Shibboleth SSO Discovery URL: $SHIB_SSO_DS_URL"

if [ -z "$SHIB_METADATA_PROVIDER_URI" ] ; then
  if [ "$ENV" != "prod" ] ; then
    SHIB_METADATA_PROVIDER_URI=https://${SHIB_IDP_DOMAINNAME}/metadata/tuakiri-test-metadata-signed.xml
  else 
    SHIB_METADATA_PROVIDER_URI=https://${SHIB_IDP_DOMAINNAME}/metadata/tuakiri-metadata-signed.xml
  fi
fi
echo "Shibboleth metadata provider URI (\$SHIB_METADATA_PROVIDER_URI): $SHIB_METADATA_PROVIDER_URI"

if [ -z "$SHIB_METADATA_CERT_FILE" ] ; then
  if [ "$ENV" != "prod" ] ; then
    SHIB_METADATA_CERT_FILE=tuakiri-test-metadata-cert.pem
  else 
    SHIB_METADATA_CERT_FILE=tuakiri-metadata-cert.pem
  fi
fi
echo "Shibboleth metadata certificate file (\$SHIB_METADATA_CERT_FILE): $SHIB_METADATA_CERT_FILE"

export ENV SHIB_SP_DOMAINNAME SHIB_IDP_DOMAINNAME SHIB_SSO_DS_URL SHIB_METADATA_PROVIDER_URI
export SHIB_METADATA_CERT_FILE

if [ ! -f /etc/shibboleth/sp-key.pem ] || [ ! -f /etc/shibboleth/sp-cert.pem ] ; then
  cd /etc/shibboleth
  ./keygen.sh -f -h $SHIB_SP_DOMAINNAME -e https://$SHIB_SP_DOMAINNAME/shibboleth
fi

cp /.keys/${ENV}-server.key /etc/pki/tls/private/server.key
chown root /etc/pki/tls/private/server.key
chmod 400 /etc/pki/tls/private/server.key
cp /.keys/${ENV}-server.crt /etc/pki/tls/certs/server.crt
chown root /etc/pki/tls/certs/server.crt
cp /.keys/CA.crt /etc/pki/tls/certs/CA.crt

echo "Rendering Shibboleth configuration template ..."
/conf/render_template /conf/templates/shibboleth2.xml >/etc/shibboleth/shibboleth2.xml

# Create a dirctory for application logs:
mkdir -p /var/log/orcidhub
chown -R apache:apache /var/log/orcidhub

# Run Shibboleth and Apache:
echo "Starting Shibboleth ..."
/etc/shibboleth/shibd-redhat start
rm -f /run/httpd/httpd.pid /usr/local/apache2/logs/httpd.pid /var/lock/subsys/shibd
echo "Starting Apache2 ..."
exec httpd -DFOREGROUND
