#!/bin/bash

# host domainnname:
ENV=${ENV:-test}
DOMAINNAME=${DOMAINNAME-$(hostname -A)}
[ -z "$SP_DOMAINNAME" ] && SP_DOMAINNAME=${DOMAINNAME/$HOSTNAME/$ENV}
echo "SP Domainname: $SP_DOMAINNAME"

cd /etc/shibboleth
./keygen.sh -f -h $DOMAINNAME -e https://$DOMAINNAME/shibboleth

# TODO: set-up the rest of configuration for the specific configuration
# shibboleth2.xml and attribute-map.xml


/etc/shibboleth/shibd-redhat start
rm -f /usr/local/apache2/logs/httpd.pid /var/lock/subsys/shibd
exec httpd -DFOREGROUND
