# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.funding_summary import FundingSummary


class TestFundingSummary(unittest.TestCase):
    """ FundingSummary unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundingSummary(self):
        """
        Test FundingSummary
        """
        model = swagger_client.models.funding_summary.FundingSummary()


if __name__ == '__main__':
    unittest.main()
