# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.person_external_identifier import PersonExternalIdentifier


class TestPersonExternalIdentifier(unittest.TestCase):
    """ PersonExternalIdentifier unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonExternalIdentifier(self):
        """
        Test PersonExternalIdentifier
        """
        model = swagger_client.models.person_external_identifier.PersonExternalIdentifier()


if __name__ == '__main__':
    unittest.main()
