# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.items import Items


class TestItems(unittest.TestCase):
    """ Items unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItems(self):
        """
        Test Items
        """
        model = swagger_client.models.items.Items()


if __name__ == '__main__':
    unittest.main()
