# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.member_apiv21_api import MemberAPIV21Api


class TestMemberAPIV21Api(unittest.TestCase):
    """ MemberAPIV21Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.member_apiv21_api.MemberAPIV21Api()

    def tearDown(self):
        pass

    def test_add_permission_notification(self):
        """
        Test case for add_permission_notification

        Add a notification
        """
        pass

    def test_create_address(self):
        """
        Test case for create_address

        Add an address
        """
        pass

    def test_create_education(self):
        """
        Test case for create_education

        Create an Education
        """
        pass

    def test_create_employment(self):
        """
        Test case for create_employment

        Create an Employment
        """
        pass

    def test_create_external_identifier(self):
        """
        Test case for create_external_identifier

        Add external identifier
        """
        pass

    def test_create_funding(self):
        """
        Test case for create_funding

        Create a Funding
        """
        pass

    def test_create_group_id_record(self):
        """
        Test case for create_group_id_record

        Create a Group
        """
        pass

    def test_create_keyword(self):
        """
        Test case for create_keyword

        Add keyword
        """
        pass

    def test_create_other_name(self):
        """
        Test case for create_other_name

        Add other name
        """
        pass

    def test_create_peer_review(self):
        """
        Test case for create_peer_review

        Create a Peer Review
        """
        pass

    def test_create_researcher_url(self):
        """
        Test case for create_researcher_url

        Add a new researcher url for an ORCID ID
        """
        pass

    def test_create_work(self):
        """
        Test case for create_work

        Create a Work
        """
        pass

    def test_create_works(self):
        """
        Test case for create_works

        Create a listo of Work
        """
        pass

    def test_delete_address(self):
        """
        Test case for delete_address

        Delete an address
        """
        pass

    def test_delete_education(self):
        """
        Test case for delete_education

        Delete an Education
        """
        pass

    def test_delete_employment(self):
        """
        Test case for delete_employment

        Delete an Employment
        """
        pass

    def test_delete_external_identifier(self):
        """
        Test case for delete_external_identifier

        Delete external identifier
        """
        pass

    def test_delete_funding(self):
        """
        Test case for delete_funding

        Delete a Funding
        """
        pass

    def test_delete_group_id_record(self):
        """
        Test case for delete_group_id_record

        Delete a Group
        """
        pass

    def test_delete_keyword(self):
        """
        Test case for delete_keyword

        Delete keyword
        """
        pass

    def test_delete_other_name(self):
        """
        Test case for delete_other_name

        Delete other name
        """
        pass

    def test_delete_peer_review(self):
        """
        Test case for delete_peer_review

        Delete a Peer Review
        """
        pass

    def test_delete_researcher_url(self):
        """
        Test case for delete_researcher_url

        Delete one researcher url from an ORCID ID
        """
        pass

    def test_delete_work(self):
        """
        Test case for delete_work

        Delete a Work
        """
        pass

    def test_edit_address(self):
        """
        Test case for edit_address

        Edit an address
        """
        pass

    def test_edit_external_identifier(self):
        """
        Test case for edit_external_identifier

        Edit external identifier
        """
        pass

    def test_edit_keyword(self):
        """
        Test case for edit_keyword

        Edit keyword
        """
        pass

    def test_edit_other_name(self):
        """
        Test case for edit_other_name

        Edit other name
        """
        pass

    def test_edit_researcher_url(self):
        """
        Test case for edit_researcher_url

        Edits researcher url for an ORCID ID
        """
        pass

    def test_flag_as_archived_permission_notification(self):
        """
        Test case for flag_as_archived_permission_notification

        Archive a notification
        """
        pass

    def test_search_by_query_xml(self):
        """
        Test case for search_by_query_xml

        Search records
        """
        pass

    def test_update_education(self):
        """
        Test case for update_education

        Update an Education
        """
        pass

    def test_update_employment(self):
        """
        Test case for update_employment

        Update an Employment
        """
        pass

    def test_update_funding(self):
        """
        Test case for update_funding

        Update a Funding
        """
        pass

    def test_update_group_id_record(self):
        """
        Test case for update_group_id_record

        Update a Group
        """
        pass

    def test_update_peer_review(self):
        """
        Test case for update_peer_review

        Update a Peer Review
        """
        pass

    def test_update_work(self):
        """
        Test case for update_work

        Update a Work
        """
        pass

    def test_view_activities(self):
        """
        Test case for view_activities

        Fetch all activities
        """
        pass

    def test_view_address(self):
        """
        Test case for view_address

        Fetch an address
        """
        pass

    def test_view_addresses(self):
        """
        Test case for view_addresses

        Fetch all addresses of a profile
        """
        pass

    def test_view_biography(self):
        """
        Test case for view_biography

        Get biography details
        """
        pass

    def test_view_client(self):
        """
        Test case for view_client

        Fetch client details
        """
        pass

    def test_view_education(self):
        """
        Test case for view_education

        Fetch an Education
        """
        pass

    def test_view_education_summary(self):
        """
        Test case for view_education_summary

        Fetch an Education summary
        """
        pass

    def test_view_educations(self):
        """
        Test case for view_educations

        Fetch all educations
        """
        pass

    def test_view_emails(self):
        """
        Test case for view_emails

        Fetch all emails for an ORCID ID
        """
        pass

    def test_view_employment(self):
        """
        Test case for view_employment

        Fetch an Employment
        """
        pass

    def test_view_employment_summary(self):
        """
        Test case for view_employment_summary

        Fetch an Employment Summary
        """
        pass

    def test_view_employments(self):
        """
        Test case for view_employments

        Fetch all employments
        """
        pass

    def test_view_external_identifier(self):
        """
        Test case for view_external_identifier

        Fetch external identifier
        """
        pass

    def test_view_external_identifiers(self):
        """
        Test case for view_external_identifiers

        Fetch external identifiers
        """
        pass

    def test_view_funding(self):
        """
        Test case for view_funding

        Fetch a Funding
        """
        pass

    def test_view_funding_summary(self):
        """
        Test case for view_funding_summary

        Fetch a Funding Summary
        """
        pass

    def test_view_fundings(self):
        """
        Test case for view_fundings

        Fetch all fundings
        """
        pass

    def test_view_group_id_record(self):
        """
        Test case for view_group_id_record

        Fetch a Group
        """
        pass

    def test_view_group_id_records(self):
        """
        Test case for view_group_id_records

        Fetch Groups
        """
        pass

    def test_view_keyword(self):
        """
        Test case for view_keyword

        Fetch keyword
        """
        pass

    def test_view_keywords(self):
        """
        Test case for view_keywords

        Fetch keywords
        """
        pass

    def test_view_other_name(self):
        """
        Test case for view_other_name

        Fetch Other name
        """
        pass

    def test_view_other_names(self):
        """
        Test case for view_other_names

        Fetch Other names
        """
        pass

    def test_view_peer_review(self):
        """
        Test case for view_peer_review

        Fetch a Peer Review
        """
        pass

    def test_view_peer_review_summary(self):
        """
        Test case for view_peer_review_summary

        Fetch a Peer Review Summary
        """
        pass

    def test_view_peer_reviews(self):
        """
        Test case for view_peer_reviews

        Fetch all peer reviews
        """
        pass

    def test_view_permission_notification(self):
        """
        Test case for view_permission_notification

        Fetch a notification by id
        """
        pass

    def test_view_person(self):
        """
        Test case for view_person

        Fetch person details
        """
        pass

    def test_view_personal_details(self):
        """
        Test case for view_personal_details

        Fetch personal details for an ORCID ID
        """
        pass

    def test_view_record(self):
        """
        Test case for view_record

        Fetch record details
        """
        pass

    def test_view_researcher_url(self):
        """
        Test case for view_researcher_url

        Fetch one researcher url for an ORCID ID
        """
        pass

    def test_view_researcher_urls(self):
        """
        Test case for view_researcher_urls

        Fetch all researcher urls for an ORCID ID
        """
        pass

    def test_view_specified_works(self):
        """
        Test case for view_specified_works

        Fetch specified works
        """
        pass

    def test_view_work(self):
        """
        Test case for view_work

        Fetch a Work
        """
        pass

    def test_view_work_summary(self):
        """
        Test case for view_work_summary

        Fetch a Work Summary
        """
        pass

    def test_view_works(self):
        """
        Test case for view_works

        Fetch all works
        """
        pass


if __name__ == '__main__':
    unittest.main()
