# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.organization_address import OrganizationAddress


class TestOrganizationAddress(unittest.TestCase):
    """ OrganizationAddress unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationAddress(self):
        """
        Test OrganizationAddress
        """
        model = swagger_client.models.organization_address.OrganizationAddress()


if __name__ == '__main__':
    unittest.main()
