# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FundingTitle(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, title=None, translated_title=None):
        """
        FundingTitle - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'title': 'Title',
            'translated_title': 'TranslatedTitle'
        }

        self.attribute_map = {
            'title': 'title',
            'translated_title': 'translated-title'
        }

        self._title = title
        self._translated_title = translated_title

    @property
    def title(self):
        """
        Gets the title of this FundingTitle.

        :return: The title of this FundingTitle.
        :rtype: Title
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this FundingTitle.

        :param title: The title of this FundingTitle.
        :type: Title
        """

        self._title = title

    @property
    def translated_title(self):
        """
        Gets the translated_title of this FundingTitle.

        :return: The translated_title of this FundingTitle.
        :rtype: TranslatedTitle
        """
        return self._translated_title

    @translated_title.setter
    def translated_title(self, translated_title):
        """
        Sets the translated_title of this FundingTitle.

        :param translated_title: The translated_title of this FundingTitle.
        :type: TranslatedTitle
        """

        self._translated_title = translated_title

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FundingTitle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
