# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FundingSummary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, created_date=None, last_modified_date=None, source=None, title=None, external_ids=None, type=None, start_date=None, end_date=None, organization=None, visibility=None, put_code=None, path=None, display_index=None):
        """
        FundingSummary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'created_date': 'CreatedDate',
            'last_modified_date': 'LastModifiedDate',
            'source': 'Source',
            'title': 'FundingTitle',
            'external_ids': 'ExternalIDs',
            'type': 'str',
            'start_date': 'FuzzyDate',
            'end_date': 'FuzzyDate',
            'organization': 'Organization',
            'visibility': 'str',
            'put_code': 'int',
            'path': 'str',
            'display_index': 'str'
        }

        self.attribute_map = {
            'created_date': 'created-date',
            'last_modified_date': 'last-modified-date',
            'source': 'source',
            'title': 'title',
            'external_ids': 'external-ids',
            'type': 'type',
            'start_date': 'start-date',
            'end_date': 'end-date',
            'organization': 'organization',
            'visibility': 'visibility',
            'put_code': 'put-code',
            'path': 'path',
            'display_index': 'display-index'
        }

        self._created_date = created_date
        self._last_modified_date = last_modified_date
        self._source = source
        self._title = title
        self._external_ids = external_ids
        self._type = type
        self._start_date = start_date
        self._end_date = end_date
        self._organization = organization
        self._visibility = visibility
        self._put_code = put_code
        self._path = path
        self._display_index = display_index

    @property
    def created_date(self):
        """
        Gets the created_date of this FundingSummary.

        :return: The created_date of this FundingSummary.
        :rtype: CreatedDate
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this FundingSummary.

        :param created_date: The created_date of this FundingSummary.
        :type: CreatedDate
        """

        self._created_date = created_date

    @property
    def last_modified_date(self):
        """
        Gets the last_modified_date of this FundingSummary.

        :return: The last_modified_date of this FundingSummary.
        :rtype: LastModifiedDate
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date):
        """
        Sets the last_modified_date of this FundingSummary.

        :param last_modified_date: The last_modified_date of this FundingSummary.
        :type: LastModifiedDate
        """

        self._last_modified_date = last_modified_date

    @property
    def source(self):
        """
        Gets the source of this FundingSummary.

        :return: The source of this FundingSummary.
        :rtype: Source
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this FundingSummary.

        :param source: The source of this FundingSummary.
        :type: Source
        """

        self._source = source

    @property
    def title(self):
        """
        Gets the title of this FundingSummary.

        :return: The title of this FundingSummary.
        :rtype: FundingTitle
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this FundingSummary.

        :param title: The title of this FundingSummary.
        :type: FundingTitle
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def external_ids(self):
        """
        Gets the external_ids of this FundingSummary.

        :return: The external_ids of this FundingSummary.
        :rtype: ExternalIDs
        """
        return self._external_ids

    @external_ids.setter
    def external_ids(self, external_ids):
        """
        Sets the external_ids of this FundingSummary.

        :param external_ids: The external_ids of this FundingSummary.
        :type: ExternalIDs
        """

        self._external_ids = external_ids

    @property
    def type(self):
        """
        Gets the type of this FundingSummary.

        :return: The type of this FundingSummary.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this FundingSummary.

        :param type: The type of this FundingSummary.
        :type: str
        """
        allowed_values = ["GRANT", "CONTRACT", "AWARD", "SALARY_AWARD"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def start_date(self):
        """
        Gets the start_date of this FundingSummary.

        :return: The start_date of this FundingSummary.
        :rtype: FuzzyDate
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """
        Sets the start_date of this FundingSummary.

        :param start_date: The start_date of this FundingSummary.
        :type: FuzzyDate
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """
        Gets the end_date of this FundingSummary.

        :return: The end_date of this FundingSummary.
        :rtype: FuzzyDate
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """
        Sets the end_date of this FundingSummary.

        :param end_date: The end_date of this FundingSummary.
        :type: FuzzyDate
        """

        self._end_date = end_date

    @property
    def organization(self):
        """
        Gets the organization of this FundingSummary.

        :return: The organization of this FundingSummary.
        :rtype: Organization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """
        Sets the organization of this FundingSummary.

        :param organization: The organization of this FundingSummary.
        :type: Organization
        """
        if organization is None:
            raise ValueError("Invalid value for `organization`, must not be `None`")

        self._organization = organization

    @property
    def visibility(self):
        """
        Gets the visibility of this FundingSummary.

        :return: The visibility of this FundingSummary.
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """
        Sets the visibility of this FundingSummary.

        :param visibility: The visibility of this FundingSummary.
        :type: str
        """
        allowed_values = ["LIMITED", "REGISTERED_ONLY", "PUBLIC", "PRIVATE"]
        if visibility not in allowed_values:
            raise ValueError(
                "Invalid value for `visibility` ({0}), must be one of {1}"
                .format(visibility, allowed_values)
            )

        self._visibility = visibility

    @property
    def put_code(self):
        """
        Gets the put_code of this FundingSummary.

        :return: The put_code of this FundingSummary.
        :rtype: int
        """
        return self._put_code

    @put_code.setter
    def put_code(self, put_code):
        """
        Sets the put_code of this FundingSummary.

        :param put_code: The put_code of this FundingSummary.
        :type: int
        """

        self._put_code = put_code

    @property
    def path(self):
        """
        Gets the path of this FundingSummary.

        :return: The path of this FundingSummary.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this FundingSummary.

        :param path: The path of this FundingSummary.
        :type: str
        """

        self._path = path

    @property
    def display_index(self):
        """
        Gets the display_index of this FundingSummary.

        :return: The display_index of this FundingSummary.
        :rtype: str
        """
        return self._display_index

    @display_index.setter
    def display_index(self, display_index):
        """
        Sets the display_index of this FundingSummary.

        :param display_index: The display_index of this FundingSummary.
        :type: str
        """

        self._display_index = display_index

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FundingSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
