# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NotificationPermission(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, put_code=None, notification_type=None, authorization_url=None, notification_subject=None, notification_intro=None, items=None, created_date=None, sent_date=None, read_date=None, actioned_date=None, archived_date=None, source=None):
        """
        NotificationPermission - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'put_code': 'int',
            'notification_type': 'str',
            'authorization_url': 'AuthorizationUrl',
            'notification_subject': 'str',
            'notification_intro': 'str',
            'items': 'Items',
            'created_date': 'datetime',
            'sent_date': 'datetime',
            'read_date': 'datetime',
            'actioned_date': 'datetime',
            'archived_date': 'datetime',
            'source': 'Source'
        }

        self.attribute_map = {
            'put_code': 'put-code',
            'notification_type': 'notification-type',
            'authorization_url': 'authorization-url',
            'notification_subject': 'notification-subject',
            'notification_intro': 'notification-intro',
            'items': 'items',
            'created_date': 'created-date',
            'sent_date': 'sent-date',
            'read_date': 'read-date',
            'actioned_date': 'actioned-date',
            'archived_date': 'archived-date',
            'source': 'source'
        }

        self._put_code = put_code
        self._notification_type = notification_type
        self._authorization_url = authorization_url
        self._notification_subject = notification_subject
        self._notification_intro = notification_intro
        self._items = items
        self._created_date = created_date
        self._sent_date = sent_date
        self._read_date = read_date
        self._actioned_date = actioned_date
        self._archived_date = archived_date
        self._source = source

    @property
    def put_code(self):
        """
        Gets the put_code of this NotificationPermission.

        :return: The put_code of this NotificationPermission.
        :rtype: int
        """
        return self._put_code

    @put_code.setter
    def put_code(self, put_code):
        """
        Sets the put_code of this NotificationPermission.

        :param put_code: The put_code of this NotificationPermission.
        :type: int
        """

        self._put_code = put_code

    @property
    def notification_type(self):
        """
        Gets the notification_type of this NotificationPermission.

        :return: The notification_type of this NotificationPermission.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type):
        """
        Sets the notification_type of this NotificationPermission.

        :param notification_type: The notification_type of this NotificationPermission.
        :type: str
        """
        allowed_values = ["CUSTOM", "INSTITUTIONAL_CONNECTION", "PERMISSION", "AMENDED"]
        if notification_type not in allowed_values:
            raise ValueError(
                "Invalid value for `notification_type` ({0}), must be one of {1}"
                .format(notification_type, allowed_values)
            )

        self._notification_type = notification_type

    @property
    def authorization_url(self):
        """
        Gets the authorization_url of this NotificationPermission.

        :return: The authorization_url of this NotificationPermission.
        :rtype: AuthorizationUrl
        """
        return self._authorization_url

    @authorization_url.setter
    def authorization_url(self, authorization_url):
        """
        Sets the authorization_url of this NotificationPermission.

        :param authorization_url: The authorization_url of this NotificationPermission.
        :type: AuthorizationUrl
        """
        if authorization_url is None:
            raise ValueError("Invalid value for `authorization_url`, must not be `None`")

        self._authorization_url = authorization_url

    @property
    def notification_subject(self):
        """
        Gets the notification_subject of this NotificationPermission.

        :return: The notification_subject of this NotificationPermission.
        :rtype: str
        """
        return self._notification_subject

    @notification_subject.setter
    def notification_subject(self, notification_subject):
        """
        Sets the notification_subject of this NotificationPermission.

        :param notification_subject: The notification_subject of this NotificationPermission.
        :type: str
        """

        self._notification_subject = notification_subject

    @property
    def notification_intro(self):
        """
        Gets the notification_intro of this NotificationPermission.

        :return: The notification_intro of this NotificationPermission.
        :rtype: str
        """
        return self._notification_intro

    @notification_intro.setter
    def notification_intro(self, notification_intro):
        """
        Sets the notification_intro of this NotificationPermission.

        :param notification_intro: The notification_intro of this NotificationPermission.
        :type: str
        """

        self._notification_intro = notification_intro

    @property
    def items(self):
        """
        Gets the items of this NotificationPermission.

        :return: The items of this NotificationPermission.
        :rtype: Items
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this NotificationPermission.

        :param items: The items of this NotificationPermission.
        :type: Items
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items

    @property
    def created_date(self):
        """
        Gets the created_date of this NotificationPermission.

        :return: The created_date of this NotificationPermission.
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this NotificationPermission.

        :param created_date: The created_date of this NotificationPermission.
        :type: datetime
        """

        self._created_date = created_date

    @property
    def sent_date(self):
        """
        Gets the sent_date of this NotificationPermission.

        :return: The sent_date of this NotificationPermission.
        :rtype: datetime
        """
        return self._sent_date

    @sent_date.setter
    def sent_date(self, sent_date):
        """
        Sets the sent_date of this NotificationPermission.

        :param sent_date: The sent_date of this NotificationPermission.
        :type: datetime
        """

        self._sent_date = sent_date

    @property
    def read_date(self):
        """
        Gets the read_date of this NotificationPermission.

        :return: The read_date of this NotificationPermission.
        :rtype: datetime
        """
        return self._read_date

    @read_date.setter
    def read_date(self, read_date):
        """
        Sets the read_date of this NotificationPermission.

        :param read_date: The read_date of this NotificationPermission.
        :type: datetime
        """

        self._read_date = read_date

    @property
    def actioned_date(self):
        """
        Gets the actioned_date of this NotificationPermission.

        :return: The actioned_date of this NotificationPermission.
        :rtype: datetime
        """
        return self._actioned_date

    @actioned_date.setter
    def actioned_date(self, actioned_date):
        """
        Sets the actioned_date of this NotificationPermission.

        :param actioned_date: The actioned_date of this NotificationPermission.
        :type: datetime
        """

        self._actioned_date = actioned_date

    @property
    def archived_date(self):
        """
        Gets the archived_date of this NotificationPermission.

        :return: The archived_date of this NotificationPermission.
        :rtype: datetime
        """
        return self._archived_date

    @archived_date.setter
    def archived_date(self, archived_date):
        """
        Sets the archived_date of this NotificationPermission.

        :param archived_date: The archived_date of this NotificationPermission.
        :type: datetime
        """

        self._archived_date = archived_date

    @property
    def source(self):
        """
        Gets the source of this NotificationPermission.

        :return: The source of this NotificationPermission.
        :rtype: Source
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this NotificationPermission.

        :param source: The source of this NotificationPermission.
        :type: Source
        """

        self._source = source

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NotificationPermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
