# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WorkSummary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, put_code=None, created_date=None, last_modified_date=None, source=None, title=None, external_ids=None, type=None, publication_date=None, journal_title=None, visibility=None, path=None, display_index=None):
        """
        WorkSummary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'put_code': 'int',
            'created_date': 'object',
            'last_modified_date': 'object',
            'source': 'object',
            'title': 'object',
            'external_ids': 'object',
            'type': 'object',
            'publication_date': 'object',
            'journal_title': 'object',
            'visibility': 'str',
            'path': 'str',
            'display_index': 'str'
        }

        self.attribute_map = {
            'put_code': 'put-code',
            'created_date': 'created-date',
            'last_modified_date': 'last-modified-date',
            'source': 'source',
            'title': 'title',
            'external_ids': 'external-ids',
            'type': 'type',
            'publication_date': 'publication-date',
            'journal_title': 'journal-title',
            'visibility': 'visibility',
            'path': 'path',
            'display_index': 'display-index'
        }

        self._put_code = put_code
        self._created_date = created_date
        self._last_modified_date = last_modified_date
        self._source = source
        self._title = title
        self._external_ids = external_ids
        self._type = type
        self._publication_date = publication_date
        self._journal_title = journal_title
        self._visibility = visibility
        self._path = path
        self._display_index = display_index

    @property
    def put_code(self):
        """
        Gets the put_code of this WorkSummary.

        :return: The put_code of this WorkSummary.
        :rtype: int
        """
        return self._put_code

    @put_code.setter
    def put_code(self, put_code):
        """
        Sets the put_code of this WorkSummary.

        :param put_code: The put_code of this WorkSummary.
        :type: int
        """

        self._put_code = put_code

    @property
    def created_date(self):
        """
        Gets the created_date of this WorkSummary.

        :return: The created_date of this WorkSummary.
        :rtype: object
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this WorkSummary.

        :param created_date: The created_date of this WorkSummary.
        :type: object
        """

        self._created_date = created_date

    @property
    def last_modified_date(self):
        """
        Gets the last_modified_date of this WorkSummary.

        :return: The last_modified_date of this WorkSummary.
        :rtype: object
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date):
        """
        Sets the last_modified_date of this WorkSummary.

        :param last_modified_date: The last_modified_date of this WorkSummary.
        :type: object
        """

        self._last_modified_date = last_modified_date

    @property
    def source(self):
        """
        Gets the source of this WorkSummary.

        :return: The source of this WorkSummary.
        :rtype: object
        """
        return self._source

    @source.setter
    def source(self, source):
        """
        Sets the source of this WorkSummary.

        :param source: The source of this WorkSummary.
        :type: object
        """

        self._source = source

    @property
    def title(self):
        """
        Gets the title of this WorkSummary.

        :return: The title of this WorkSummary.
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this WorkSummary.

        :param title: The title of this WorkSummary.
        :type: object
        """

        self._title = title

    @property
    def external_ids(self):
        """
        Gets the external_ids of this WorkSummary.

        :return: The external_ids of this WorkSummary.
        :rtype: object
        """
        return self._external_ids

    @external_ids.setter
    def external_ids(self, external_ids):
        """
        Sets the external_ids of this WorkSummary.

        :param external_ids: The external_ids of this WorkSummary.
        :type: object
        """

        self._external_ids = external_ids

    @property
    def type(self):
        """
        Gets the type of this WorkSummary.

        :return: The type of this WorkSummary.
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this WorkSummary.

        :param type: The type of this WorkSummary.
        :type: object
        """

        self._type = type

    @property
    def publication_date(self):
        """
        Gets the publication_date of this WorkSummary.

        :return: The publication_date of this WorkSummary.
        :rtype: object
        """
        return self._publication_date

    @publication_date.setter
    def publication_date(self, publication_date):
        """
        Sets the publication_date of this WorkSummary.

        :param publication_date: The publication_date of this WorkSummary.
        :type: object
        """

        self._publication_date = publication_date

    @property
    def journal_title(self):
        """
        Gets the journal_title of this WorkSummary.

        :return: The journal_title of this WorkSummary.
        :rtype: object
        """
        return self._journal_title

    @journal_title.setter
    def journal_title(self, journal_title):
        """
        Sets the journal_title of this WorkSummary.

        :param journal_title: The journal_title of this WorkSummary.
        :type: object
        """

        self._journal_title = journal_title

    @property
    def visibility(self):
        """
        Gets the visibility of this WorkSummary.

        :return: The visibility of this WorkSummary.
        :rtype: str
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """
        Sets the visibility of this WorkSummary.

        :param visibility: The visibility of this WorkSummary.
        :type: str
        """
        allowed_values = ["LIMITED", "REGISTERED_ONLY", "PUBLIC", "PRIVATE"]
        if visibility not in allowed_values:
            raise ValueError(
                "Invalid value for `visibility` ({0}), must be one of {1}"
                .format(visibility, allowed_values)
            )

        self._visibility = visibility

    @property
    def path(self):
        """
        Gets the path of this WorkSummary.

        :return: The path of this WorkSummary.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this WorkSummary.

        :param path: The path of this WorkSummary.
        :type: str
        """

        self._path = path

    @property
    def display_index(self):
        """
        Gets the display_index of this WorkSummary.

        :return: The display_index of this WorkSummary.
        :rtype: str
        """
        return self._display_index

    @display_index.setter
    def display_index(self, display_index):
        """
        Sets the display_index of this WorkSummary.

        :param display_index: The display_index of this WorkSummary.
        :type: str
        """

        self._display_index = display_index

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WorkSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
