# coding: utf-8

"""
    ORCID Member

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: Latest
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TransientError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'str',
        'error_message': 'str',
        'transient': 'bool'
    }

    attribute_map = {
        'error_code': 'error-code',
        'error_message': 'error-message',
        'transient': 'transient'
    }

    def __init__(self, error_code=None, error_message=None, transient=None):  # noqa: E501
        """TransientError - a model defined in Swagger"""  # noqa: E501
        self._error_code = None
        self._error_message = None
        self._transient = None
        self.discriminator = None
        self.error_code = error_code
        self.error_message = error_message
        self.transient = transient

    @property
    def error_code(self):
        """Gets the error_code of this TransientError.  # noqa: E501


        :return: The error_code of this TransientError.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this TransientError.


        :param error_code: The error_code of this TransientError.  # noqa: E501
        :type: str
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def error_message(self):
        """Gets the error_message of this TransientError.  # noqa: E501


        :return: The error_message of this TransientError.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this TransientError.


        :param error_message: The error_message of this TransientError.  # noqa: E501
        :type: str
        """
        if error_message is None:
            raise ValueError("Invalid value for `error_message`, must not be `None`")  # noqa: E501

        self._error_message = error_message

    @property
    def transient(self):
        """Gets the transient of this TransientError.  # noqa: E501


        :return: The transient of this TransientError.  # noqa: E501
        :rtype: bool
        """
        return self._transient

    @transient.setter
    def transient(self, transient):
        """Sets the transient of this TransientError.


        :param transient: The transient of this TransientError.  # noqa: E501
        :type: bool
        """
        if transient is None:
            raise ValueError("Invalid value for `transient`, must not be `None`")  # noqa: E501

        self._transient = transient

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransientError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransientError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
