{
  "swagger" : "2.0",
  "info" : {
    "version" : "Latest",
    "title" : "ORCID Member"
  },
  "host" : "api.orcid.org",
  "tags" : [ {
    "name" : "Member API v2.0"
  }, {
    "name" : "Member API v2.1"
  }, {
    "name" : "Development Member API v3.0"
  }, {
    "name" : "Development Member API v3.0_rc1"
  }, {
    "name" : "Development Member API v3.0_rc2"
  }, {
    "name" : "resources"
  } ],
  "paths" : {
    "/v2.0/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.0/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotification",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.0/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherName",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeyword",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWork",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFunding",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducation",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducation",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducation",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmployment",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmployment",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.0/group-id-record" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecords",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecord",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/address" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddresses",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNames",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherName",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywords",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeyword",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiers",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifier",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrls",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrl",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWork",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/works" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorks",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a list of Work",
        "description" : "",
        "operationId" : "createWorks",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFunding",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReview",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReview",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivities",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummary",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundings",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummary",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducations",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummary",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmployments",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummary",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviews",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/email" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmails",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetails",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummary",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorks",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddress",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddress",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.0/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiography",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}/person" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPerson",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/{orcid}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecord",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.0/search" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQuery",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.0/client/{client_id}" : {
      "get" : {
        "tags" : [ "Member API v2.0" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClient",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.1/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotificationV21",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotificationV21",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.1/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationV21",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v2.1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrlV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNameV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNameV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherNameV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifierV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeywordV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWorkV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWorkV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFundingV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducationV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmploymentV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmploymentV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecordV21",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordV21",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecordV21",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.1/group-id-record" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecordsV21",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordV21",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddressesV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNameV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a list of Work",
        "description" : "",
        "operationId" : "createWorksV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReviewV21",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivitiesV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummaryV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddressV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddressV21",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v2.1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/{orcid}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordV21",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v2.1/search" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryV21",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v2.1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Member API v2.1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientV21",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0/{orcid}/service" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Service",
        "description" : "",
        "operationId" : "createServicev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotificationv3",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotificationv3",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationv3",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrlv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNamev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNamev3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherNamev3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifierv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeywordv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWorkv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWorkv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFundingv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/education" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducationv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmploymentv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmploymentv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecordv3",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordv3",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecordv3",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0/group-id-record" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecordsv3",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordv3",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddressesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNamev3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/work" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorksv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReviewv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Membership",
        "description" : "",
        "operationId" : "updateMembershipv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Membership",
        "description" : "",
        "operationId" : "deleteMembershipv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualification" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Qualification",
        "description" : "",
        "operationId" : "createQualificationv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Qualification",
        "description" : "",
        "operationId" : "updateQualificationv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Qualification",
        "description" : "",
        "operationId" : "deleteQualificationv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServicev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Service",
        "description" : "",
        "operationId" : "updateServicev3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Service",
        "description" : "",
        "operationId" : "deleteServicev3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourcev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update a Research Resource",
        "description" : "",
        "operationId" : "updateResearchResourcev3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Research Resource",
        "description" : "",
        "operationId" : "deleteResearchResourcev3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivitiesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddressv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddressv3",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/search" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientv3",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0/apiStatus" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an Distinction",
        "description" : "",
        "operationId" : "updateDistinctionv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an Distinction",
        "description" : "",
        "operationId" : "deleteDistinctionv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Update an InvitedPosition",
        "description" : "",
        "operationId" : "updateInvitedPositionv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Delete an InvitedPosition",
        "description" : "",
        "operationId" : "deleteInvitedPositionv3",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/research-resource" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create a Research Resource",
        "description" : "",
        "operationId" : "createResearchResourcev3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/distinction" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Distinction",
        "description" : "",
        "operationId" : "createDistinctionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/invited-position" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an InvitedPosition",
        "description" : "",
        "operationId" : "createInvitedPositionv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0/{orcid}/membership" : {
      "post" : {
        "tags" : [ "Development Member API v3.0" ],
        "summary" : "Create an Membership",
        "description" : "",
        "operationId" : "createMembershipv3",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/service" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Service",
        "description" : "",
        "operationId" : "createServiceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotificationV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotificationV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrlV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNameV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNameV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherNameV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifierV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeywordV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWorkV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWorkV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFundingV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/education" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmploymentV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmploymentV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecordV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecordV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_rc1/group-id-record" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecordsV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddressesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNameV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/work" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorksV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReviewV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Membership",
        "description" : "",
        "operationId" : "updateMembershipV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Membership",
        "description" : "",
        "operationId" : "deleteMembershipV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualification" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Qualification",
        "description" : "",
        "operationId" : "createQualificationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Qualification",
        "description" : "",
        "operationId" : "updateQualificationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Qualification",
        "description" : "",
        "operationId" : "deleteQualificationV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServiceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Service",
        "description" : "",
        "operationId" : "updateServiceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Service",
        "description" : "",
        "operationId" : "deleteServiceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update a Research Resource",
        "description" : "",
        "operationId" : "updateResearchResourceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Research Resource",
        "description" : "",
        "operationId" : "deleteResearchResourceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivitiesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddressV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddressV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/search" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc1/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientV3Rc1",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc1/apiStatus" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0_rc1/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an Distinction",
        "description" : "",
        "operationId" : "updateDistinctionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an Distinction",
        "description" : "",
        "operationId" : "deleteDistinctionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Update an InvitedPosition",
        "description" : "",
        "operationId" : "updateInvitedPositionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Delete an InvitedPosition",
        "description" : "",
        "operationId" : "deleteInvitedPositionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/research-resource" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create a Research Resource",
        "description" : "",
        "operationId" : "createResearchResourceV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/distinction" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Distinction",
        "description" : "",
        "operationId" : "createDistinctionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/invited-position" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an InvitedPosition",
        "description" : "",
        "operationId" : "createInvitedPositionV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc1/{orcid}/membership" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc1" ],
        "summary" : "Create an Membership",
        "description" : "",
        "operationId" : "createMembershipV3Rc1",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/service" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Service",
        "description" : "",
        "operationId" : "createServicev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/notification-permission/{id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a notification by id",
        "description" : "",
        "operationId" : "viewPermissionNotificationv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Archive a notification",
        "description" : "",
        "operationId" : "flagAsArchivedPermissionNotificationv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/notification-permission" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add a notification",
        "description" : "",
        "operationId" : "addPermissionNotificationv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/premium-notification" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/researcher-urls/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch one researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Edits researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "editResearcherUrlv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete one researcher url from an ORCID ID",
        "description" : "",
        "operationId" : "deleteResearcherUrlv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/other-names/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch Other name",
        "description" : "",
        "operationId" : "viewOtherNamev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Edit other name",
        "description" : "",
        "operationId" : "editOtherNamev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete other name",
        "description" : "",
        "operationId" : "deleteOtherNamev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/external-identifiers/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch external identifier",
        "description" : "",
        "operationId" : "viewExternalIdentifierv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Edit external identifier",
        "description" : "",
        "operationId" : "editExternalIdentifierv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete external identifier",
        "description" : "",
        "operationId" : "deleteExternalIdentifierv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/keywords/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch keyword",
        "description" : "",
        "operationId" : "viewKeywordv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Edit keyword",
        "description" : "",
        "operationId" : "editKeywordv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete keyword",
        "description" : "",
        "operationId" : "deleteKeywordv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/work/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Work",
        "description" : "",
        "operationId" : "viewWorkv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update a Work",
        "description" : "",
        "operationId" : "updateWorkv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete a Work",
        "description" : "",
        "operationId" : "deleteWorkv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/funding/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Funding",
        "description" : "",
        "operationId" : "viewFundingv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update a Funding",
        "description" : "",
        "operationId" : "updateFundingv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete a Funding",
        "description" : "",
        "operationId" : "deleteFundingv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/education" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Education",
        "description" : "",
        "operationId" : "createEducationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/education/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Education",
        "description" : "",
        "operationId" : "viewEducationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Education",
        "description" : "",
        "operationId" : "updateEducationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Education",
        "description" : "",
        "operationId" : "deleteEducationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/employment" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Employment",
        "description" : "",
        "operationId" : "createEmploymentv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/employment/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Employment",
        "description" : "",
        "operationId" : "viewEmploymentv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Employment",
        "description" : "",
        "operationId" : "updateEmploymentv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Employment",
        "description" : "",
        "operationId" : "deleteEmploymentv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/group-id-record/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Group",
        "description" : "",
        "operationId" : "viewGroupIdRecordv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update a Group",
        "description" : "",
        "operationId" : "updateGroupIdRecordv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete a Group",
        "description" : "",
        "operationId" : "deleteGroupIdRecordv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_rc2/group-id-record" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch Groups",
        "description" : "",
        "operationId" : "viewGroupIdRecordsv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a Group",
        "description" : "",
        "operationId" : "createGroupIdRecordv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/group-id-record/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/address" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all addresses of a profile",
        "description" : "",
        "operationId" : "viewAddressesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add an address",
        "description" : "",
        "operationId" : "createAddressv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/other-names" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch Other names",
        "description" : "",
        "operationId" : "viewOtherNamesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add other name",
        "description" : "",
        "operationId" : "createOtherNamev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/keywords" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch keywords",
        "description" : "",
        "operationId" : "viewKeywordsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add keyword",
        "description" : "",
        "operationId" : "createKeywordv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/external-identifiers" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch external identifiers",
        "description" : "",
        "operationId" : "viewExternalIdentifiersv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add external identifier",
        "description" : "",
        "operationId" : "createExternalIdentifierv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/researcher-urls" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all researcher urls for an ORCID ID",
        "description" : "",
        "operationId" : "viewResearcherUrlsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Add a new researcher url for an ORCID ID",
        "description" : "",
        "operationId" : "createResearcherUrlv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/work" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a Work",
        "description" : "",
        "operationId" : "createWorkv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/works" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all works",
        "description" : "",
        "operationId" : "viewWorksv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a listo of Work",
        "description" : "",
        "operationId" : "createWorksv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/funding" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a Funding",
        "description" : "",
        "operationId" : "createFundingv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/peer-review" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a Peer Review",
        "description" : "",
        "operationId" : "createPeerReviewv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/peer-review/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Peer Review",
        "description" : "",
        "operationId" : "viewPeerReviewv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update a Peer Review",
        "description" : "",
        "operationId" : "updatePeerReviewv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete a Peer Review",
        "description" : "",
        "operationId" : "deletePeerReviewv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/membership/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Membership",
        "description" : "",
        "operationId" : "viewMembershipv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Membership",
        "description" : "",
        "operationId" : "updateMembershipv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Membership",
        "description" : "",
        "operationId" : "deleteMembershipv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualification" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Qualification",
        "description" : "",
        "operationId" : "createQualificationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualification/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Qualification",
        "description" : "",
        "operationId" : "viewQualificationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Qualification",
        "description" : "",
        "operationId" : "updateQualificationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Qualification",
        "description" : "",
        "operationId" : "deleteQualificationv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/service/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Service",
        "description" : "",
        "operationId" : "viewServicev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Service",
        "description" : "",
        "operationId" : "updateServicev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Service",
        "description" : "",
        "operationId" : "deleteServicev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resource/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Research Resource",
        "description" : "",
        "operationId" : "viewResearchResourcev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update a Research Resource",
        "description" : "",
        "operationId" : "updateResearchResourcev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Research Resource",
        "description" : "",
        "operationId" : "deleteResearchResourcev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/activities" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all activities",
        "description" : "",
        "operationId" : "viewActivitiesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/funding/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Funding Summary",
        "description" : "",
        "operationId" : "viewFundingSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/fundings" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all fundings",
        "description" : "",
        "operationId" : "viewFundingsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/education/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Education summary",
        "description" : "",
        "operationId" : "viewEducationSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/educations" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all educations",
        "description" : "",
        "operationId" : "viewEducationsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/employment/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Employment Summary",
        "description" : "",
        "operationId" : "viewEmploymentSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/employments" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all employments",
        "description" : "",
        "operationId" : "viewEmploymentsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/peer-review/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Peer Review Summary",
        "description" : "",
        "operationId" : "viewPeerReviewSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/peer-reviews" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all peer reviews",
        "description" : "",
        "operationId" : "viewPeerReviewsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/email" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all emails for an ORCID ID",
        "description" : "",
        "operationId" : "viewEmailsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/personal-details" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch personal details for an ORCID ID",
        "description" : "",
        "operationId" : "viewPersonalDetailsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/work/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Work Summary",
        "description" : "",
        "operationId" : "viewWorkSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/works/{putCodes}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch specified works",
        "description" : "",
        "operationId" : "viewSpecifiedWorksv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/address/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an address",
        "description" : "",
        "operationId" : "viewAddressv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Edit an address",
        "description" : "",
        "operationId" : "editAddressv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an address",
        "description" : "",
        "operationId" : "deleteAddressv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/person/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/biography" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Get biography details",
        "description" : "",
        "operationId" : "viewBiographyv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/person" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch person details",
        "description" : "",
        "operationId" : "viewPersonv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch record details",
        "description" : "",
        "operationId" : "viewRecordv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/search" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Search records",
        "description" : "",
        "operationId" : "searchByQueryv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc2/client/{client_id}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch client details",
        "description" : "",
        "operationId" : "viewClientv3Rc2",
        "security" : [ {
          "orcid_two_legs" : [ "/read-public" ]
        } ]
      }
    },
    "/v3.0_rc2/apiStatus" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "operationId" : "viewStatusJson"
      }
    },
    "/v3.0_rc2/{orcid}/distinction/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Distinction",
        "description" : "",
        "operationId" : "viewDistinctionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an Distinction",
        "description" : "",
        "operationId" : "updateDistinctionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an Distinction",
        "description" : "",
        "operationId" : "deleteDistinctionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/distinctions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all distinctions",
        "description" : "",
        "operationId" : "viewDistinctionsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/distinction/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Distinction summary",
        "description" : "",
        "operationId" : "viewDistinctionSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-position/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an InvitedPosition",
        "description" : "",
        "operationId" : "viewInvitedPositionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      },
      "put" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Update an InvitedPosition",
        "description" : "",
        "operationId" : "updateInvitedPositionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Delete an InvitedPosition",
        "description" : "",
        "operationId" : "deleteInvitedPositionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/activities/update" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-positions" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all invitedPositions",
        "description" : "",
        "operationId" : "viewInvitedPositionsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-position/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an InvitedPosition summary",
        "description" : "",
        "operationId" : "viewInvitedPositionSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/memberships" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all memberships",
        "description" : "",
        "operationId" : "viewMembershipsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/membership/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Membership summary",
        "description" : "",
        "operationId" : "viewMembershipSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualifications" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all qualifications",
        "description" : "",
        "operationId" : "viewQualificationsv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/qualification/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Qualification summary",
        "description" : "",
        "operationId" : "viewQualificationSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/services" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all services",
        "description" : "",
        "operationId" : "viewServicesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/service/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch an Service summary",
        "description" : "",
        "operationId" : "viewServiceSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resources" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch all Research Resources",
        "description" : "",
        "operationId" : "viewResearchResourcesv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resource/summary/{putCode}" : {
      "get" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Fetch a Research Resource summary",
        "description" : "",
        "operationId" : "viewResearchResourceSummaryv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/research-resource" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create a Research Resource",
        "description" : "",
        "operationId" : "createResearchResourcev3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/distinction" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Distinction",
        "description" : "",
        "operationId" : "createDistinctionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/invited-position" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an InvitedPosition",
        "description" : "",
        "operationId" : "createInvitedPositionv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    },
    "/v3.0_rc2/{orcid}/membership" : {
      "post" : {
        "tags" : [ "Development Member API v3.0_rc2" ],
        "summary" : "Create an Membership",
        "description" : "",
        "operationId" : "createMembershipv3Rc2",
        "security" : [ {
          "orcid_auth" : [ "/read-limited" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "orcid_auth" : {
      "type" : "oauth2",
      "authorizationUrl" : "https://orcid.org/oauth/authorize",
      "tokenUrl" : "https://pub.orcid.org/oauth/token",
      "flow" : "accessCode",
      "scopes" : {
        "/read-limited" : "Read Limited record",
        "/person/update" : "Update person",
        "/activities/update" : "Update activities"
      }
    },
    "orcid_two_legs" : {
      "type" : "oauth2",
      "tokenUrl" : "https://pub.orcid.org/oauth/token",
      "flow" : "application",
      "scopes" : {
        "/premium-notification" : "Notifications",
        "/read-public" : "Read Public record",
        "/group-id-record/read" : "Read groups",
        "/group-id-record/update" : "Update groups"
      }
    }
  }
}