#!/bin/bash

# Set up the configuration:
if [ -z "$ORCID_CLIENT_ID" ] || [ -z "$ORCID_CLIENT_SECRET" ] ; then
  echo "Missing Orcid API client ID (\$ORCID_CLIENT_ID) and/or secret (\$ORCID_CLIENT_SECRET)"
  exit 78 # /* configuration error */
fi
## Runtime environment name:
ENV=${ENV:-test}
echo "Runtime Environment: $ENV"
## host domainnname:
DOMAINNAME=${DOMAINNAME:-$(hostname -A | cut -d\  -f1)}
HOSTNAME=${HOSTNAME-$(hostname)}

echo \"$DOMAINNAME\" \"$HOSTNAME\"
## Shibboleth SP domainname:
[ -z "$SHIB_SP_DOMAINNAME" ] && SHIB_SP_DOMAINNAME=${DOMAINNAME/$HOSTNAME/$ENV}
echo "Shibboleth SP Domainname: \"$SHIB_SP_DOMAINNAME\""

## Shibboleth SP domainname:
[ -z "$SHIB_IDP_DOMAINNAME" ] && SHIB_IDP_DOMAINNAME=directory.$ENV.tuakiri.ac.nz
echo "Shibboleth IdP Domainname: $SHIB_IDP_DOMAINNAME"

[ -z "$SHIB_SSO_DS_URL" ] && SHIB_SSO_DS_URL=https://${SHIB_IDP_DOMAINNAME}/ds/DS
echo "Shibboleth SSO Discovery URL: $SHIB_SSO_DS_URL"

[ -z "$SHIB_METADATA_PROVIDER_URI" ] && SHIB_METADATA_PROVIDER_URI=https://${SHIB_IDP_DOMAINNAME}/metadata/tuakiri-${ENV}-metadata-signed.xml
echo "Shibboleth metadata provider URI: $SHIB_METADATA_PROVIDER_URI"

export ENV SHIB_SP_DOMAINNAME SHIB_IDP_DOMAINNAME SHIB_SSO_DS_URL SHIB_METADATA_PROVIDER_URI

if [ ! -f /etc/shibboleth/sp-key.pem ] || [ ! -f /etc/shibboleth/sp-cert.pem ] ; then
  cd /etc/shibboleth
  ./keygen.sh -f -h $SHIB_SP_DOMAINNAME -e https://$SHIB_SP_DOMAINNAME/shibboleth
fi

/conf/render_template /conf/templates/shibboleth2.xml >/etc/shibboleth/shibboleth2.xml

# Run Shibboleth and Apache:
/etc/shibboleth/shibd-redhat start
rm -f /usr/local/apache2/logs/httpd.pid /var/lock/subsys/shibd
exec httpd -DFOREGROUND
